[package]
name = "lupineos-welcome"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.7"
libadwaita = "0.5"
gettext-rs = "0.7"
dirs = "5.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
