# LupineOS Starship Config - Ashen Theme

format = """
[â–‘â–’â–“](#a7a7a7)\
[ ğŸº ](bg:#a7a7a7 fg:#121212)\
[î‚´](bg:#949494 fg:#a7a7a7)\
$directory\
[î‚´](fg:#949494 bg:#323232)\
$git_branch\
$git_status\
[î‚´](fg:#323232 bg:#1d1d1d)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#1d1d1d bg:#151515)\
$time\
[î‚´ ](fg:#151515)\
\n$character"""

[directory]
style = "fg:#e5e5e5 bg:#949494"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#323232"
format = "[[ $symbol $branch ](fg:#C4693D bg:#323232)]($style)"

[git_status]
style = "bg:#323232"
format = "[[($all_status$ahead_behind )](fg:#C4693D bg:#323232)]($style)"

[nodejs]
symbol = "îœ˜"
style = "bg:#1d1d1d"
format = "[[ $symbol ($version) ](fg:#D87C4A bg:#1d1d1d)]($style)"

[rust]
symbol = "î¨"
style = "bg:#1d1d1d"
format = "[[ $symbol ($version) ](fg:#D87C4A bg:#1d1d1d)]($style)"

[golang]
symbol = "î˜§"
style = "bg:#1d1d1d"
format = "[[ $symbol ($version) ](fg:#D87C4A bg:#1d1d1d)]($style)"

[php]
symbol = "ï€‡"
style = "bg:#1d1d1d"
format = "[[ $symbol ($version) ](fg:#D87C4A bg:#1d1d1d)]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#151515"
format = "[[ ïº $time ](fg:#737373 bg:#151515)]($style)"
