name: Generate ISO
on:
  workflow_dispatch: # Lets you click the button manually

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.4
        with:
          # Points to the image you ALREADY built successfully
          src: ghcr.io/theexiled/lupineos:latest
          
          # Name of the output file
          iso_name: lupineos-installer
          
          # We need this to verify we own the package
          auth_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: lupineos-iso
          path: |
            ./*.iso
            ./*-CHECKSUM
          if-no-files-found: error
          retention-days: 1
