name: build-iso
on:
  workflow_dispatch: # This allows you to manually trigger the build

jobs:
  iso:
    name: Build ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        uses: blue-build/github-action@v1.8
        with:
          recipe: recipes/recipe.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          # This tells BlueBuild to output an ISO file
          iso_name: lupineos-cosmic

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: lupineos-cosmic
          path: |
            ./lupineos-cosmic*.iso
            ./lupineos-cosmic*.iso-CHECKSUM
          if-no-files-found: error
          retention-days: 5
