name: Generate ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.4
        with:
          src: ghcr.io/theexiled/lupineos:latest
          iso_name: lupineos-installer
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          # --- THE FIX IS HERE ---
          # We force it to use Fedora 41 (Stable) instead of the broken default (39)
          fedora_version: 43

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: lupineos-iso
          path: |
            ./*.iso
            ./*-CHECKSUM
          if-no-files-found: error
          retention-days: 1
